### ISSUE TITLE
Websocket 5 support

### ISSUE THREAD

**Issue by nacalai** [lebaston100/mv-stats-for-obs#2]
Greetings! Still using and loving this handy status indicator. It's pretty much vital to our productions. With websocket 5.0 coming up, would you make an adaption to support it? It goes from qt5 to qt6 which requires devs to update their plugins. I assume that these htmls are so simple that an adaption might not even be needed?

**Comment by lebaston100** [comment]
Hi. Since this is not a plugin but just a html page this is completely independed from the QT Upgrade.
For now for it to function in obs 28 you need to additionally install obs-websocket-4.9.1-compat.
I might update it in the future to use obs-websocket 5 but that will require a lot of work and will only work if all the features i need are available in that version.

**Comment by lebaston100** [comment]
Done with https://github.com/lebaston100/mv-stats-for-obs/commit/2f3d879f17ae9fe314796a106a04404944d5a350

**Comment by nacalai** [comment]
Thanks a lot dude!
